services:
  grafana:
    image: grafana/grafana-enterprise
    user: "0"
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
     - /grafana:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.ugur.com`)"
      #- "traefik.http.routers.whoami.rule=Host(`grafana.ugur.com`)"
      #- traefik.http.services.grafana.loadbalancer.server.port=3000

